# project data for Bukkit in order to register our plugin with all it components
# ${-} are variables from Maven (pom.xml) which will be replaced after the build
name: ${project.name}
version: ${project.version}
main: ${project.groupId}.${project.artifactId}.${project.name}

# meta data for plugin managers
authors: [games647, 'https://github.com/games647/mcMMOAction/graphs/contributors']
description: |
    ${project.description}
website: ${project.url}
dev-url: ${project.url}

# Without Protocollib the plugin does not work at all
depend: [ProtocolLib, mcMMO]

# This plugin don't have to be transformed for compatibility with Minecraft >= 1.13
api-version: 1.13

commands:
    mmoaction:
        description: 'Toggle the action bar display or progress feature'
        aliases: [${project.artifactId}]
        permission: '${project.artifactId}.command.toggle'

permissions:
    ${project.artifactId}.*:
        description: Gives access to all ${project.name} features
        children:
            ${project.artifactId}.commands.*: true
            ${project.artifactId}.display: true

    ${project.artifactId}.commands.*:
        description: Gives access to all ${project.name} commands
        children:
            ${project.artifactId}.command.toggle: true

    ${project.artifactId}.display:
        description: Display the message in the actionbar
        default: true
